### ISSUE TITLE
debug/index.css not getting created

### ISSUE THREAD

**Issue by ocanbascil** [locoslab/vue-typescript-component-example#39]
When I run `npm run start`, only `debug/index.js` is getting created and `debug/index.css` is missing. However `npm run mkdist` successfully creates both `index.js` and `index.css` files.

**Comment by unoexperto** [comment]
@locobert I see same thing.

`npm run mkdist` didn't help me. I got 

```
TypeScript error: node_modules/vue-typescript-component/lib/vue-typescript-component.d.ts(5,35): Error TS2304: Cannot find name 'Vue'.

```

**Comment by Andreas-Scholz** [comment]
@unoexperto Same here, `debug/index.css` is missing and `npm run mkdist` produces the same error that you get.

**Comment by locobert** [comment]
Sorry for the long overdue reply. The TypeScript bindings in Vue.js have changed considerably over time and we do not use the approach of this repository any more. We recommend to use the official TypeScript support and get started with [Vue CLI](https://cli.vuejs.org/).
